name: GeyserFlood-Updater
main: com.Alysaa.Tut.Alysaaproject
version: 0.1.1
api-version: 1.15
description: AlysaaKobe Plugin.
commands:
  geyserupdate:
    description: updating Geyser command
    usage: /geyserupdate
    permission: AlysaaPlugin.geyserupdate
  floodgateupdate:
    description: updating floodgate plugin
    usage: /floodgateupdate
    permission: AlysaaPlugin.floodgateupdate
permissions:
  AlysaaPlugin.broadcast:
    description: Broadcasts updates.
    default: op
