name: GeyserFlood-Updater
main: Alysaa.Tut.Alysaaproject
version: 0.0.2
api-version: 1.15
description: AlysaaKobe Plugin.
commands:
  geyserupdate:
    description: updating Geyser command
    usage: /geyserupdate
    permission: AlysaaPlugin.geyserupdate
  floodgateupdate:
    description: updating floodgate plugin
    usage: /floodgateupdate
    permission: AlysaaPlugin.floodgateupdate